spring:
  application:
    name: places-been
  datasource:
    url:
    username: postgres
    password: jdbc:postgresql://db.acycmykkrhbcuxvgobam.supabase.co:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    apiversion:
      supported: 1
      default: 1
      enabledd: true
      use:
        header: Api-Version